// Bill Tracker — reads tax-fairness/data/bill-status.json (generated by
// .github/workflows/fetch-bill-status.yml) instead of fetching RSS live through a CORS proxy.
// Renders two things, both driven by the same JSON:
//   1. Per-proposal mini trackers: any element matching [data-tracker-id][data-hb][data-sb]
//   2. The master "Bill Status Tracker" table: #bill-status-content, if present on the page
// See tax-fairness/README.md for how this fits together and how to add a bill.

const BillTracker = (function () {
  'use strict';

  // This script is loaded via <script src> from GitHub Pages, so a plain relative
  // fetch('data/bill-status.json') would resolve against the EMBEDDING page's origin
  // (e.g. hitaxfairness.org when pasted into Squarespace) rather than where the JSON
  // actually lives. Instead, derive it from this script's own URL via
  // document.currentScript — that's only valid while the script first executes
  // synchronously, so it's captured into a const right here at the top level, not
  // inside loadData() below. Forking this repo to a different GitHub Pages project
  // needs ZERO edits here: this always finds "data/bill-status.json" next to wherever
  // bill-tracker.js itself was loaded from.
  //
  // ?tfc_data=<url> on the page's own URL overrides this — useful for pointing a page
  // at a different environment's JSON without editing any file.
  const SELF_URL = document.currentScript ? document.currentScript.src : 'bill-tracker.js';
  const DATA_URL =
    new URLSearchParams(location.search).get('tfc_data') || new URL('data/bill-status.json', SELF_URL).href;

  let dataPromise = null;
  function loadData() {
    if (!dataPromise) {
      dataPromise = fetch(DATA_URL)
        .then((r) => (r.ok ? r.json() : Promise.reject(new Error(`HTTP ${r.status}`))))
        .catch((err) => {
          console.error(`BillTracker: failed to load ${DATA_URL}`, err);
          return null;
        });
    }
    return dataPromise;
  }

  // bill.description/error come from capitol.hawaii.gov RSS text — low-risk (it's
  // auto-generated procedural text, not user input) but it's spliced into innerHTML
  // below, so escape it rather than trust it.
  function escapeHtml(str) {
    return String(str)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#39;');
  }

  function formatDate(iso) {
    return new Date(iso).toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
  }

  // ---------- Per-proposal mini trackers ----------

  function generateTrackerHTML(trackerId, hbNumbers, sbNumbers, year) {
    const link = (type, num) =>
      `<a href="https://www.capitol.hawaii.gov/session/measure_indiv.aspx?billtype=${type}&billnumber=${num}&year=${year}" target="_blank" onclick="event.stopPropagation()">${num}</a>`;
    const hbDisplay = hbNumbers.length ? `HB <span class="hb-numbers">${hbNumbers.map((n) => link('HB', n)).join(', ')}</span>` : 'No Bill';
    const sbDisplay = sbNumbers.length ? `SB <span class="sb-numbers">${sbNumbers.map((n) => link('SB', n)).join(', ')}</span>` : 'No Bill';
    return `
      <div class="tfc-legislation-header" onclick="BillTracker.toggleTracker('${trackerId}')">
        Legislation <span class="tfc-legislation-toggle-icon"></span>
      </div>
      <div class="tfc-tracker-content" id="${trackerId}-content">
        <div class="tfc-bill-columns">
          <div class="tfc-bill-col ${hbNumbers.length ? 'active' : ''}" data-bill-type="hb" onclick="BillTracker.switchFeed('${trackerId}', 'hb')">
            <h4>House Bill${hbNumbers.length > 1 ? 's' : ''}</h4>
            <div class="tfc-bill-number">${hbDisplay}</div>
          </div>
          <div class="tfc-bill-col ${!hbNumbers.length && sbNumbers.length ? 'active' : ''}" data-bill-type="sb" onclick="BillTracker.switchFeed('${trackerId}', 'sb')">
            <h4>Senate Bill${sbNumbers.length > 1 ? 's' : ''}</h4>
            <div class="tfc-bill-number">${sbDisplay}</div>
          </div>
        </div>
        <div class="tfc-status-section" id="${trackerId}-status">
          <div class="tfc-status-header" onclick="BillTracker.toggleHistory('${trackerId}')">
            <span class="tfc-status-title">Latest Status <span class="tfc-status-badge" id="${trackerId}-badge">Loading...</span></span>
            <span class="tfc-status-toggle">History</span>
          </div>
          <div class="tfc-latest-update" id="${trackerId}-latest"><span class="tfc-loading">Loading bill status...</span></div>
          <div class="tfc-status-history" id="${trackerId}-history"></div>
        </div>
        <div class="tfc-tracker-meta">
          <span class="tfc-last-updated" id="${trackerId}-updated"></span>
        </div>
      </div>
    `;
  }

  function renderTrackerFeed(trackerId, billsData, type, numbers) {
    const latestEl = document.getElementById(`${trackerId}-latest`);
    const badgeEl = document.getElementById(`${trackerId}-badge`);
    const historyEl = document.getElementById(`${trackerId}-history`);
    if (!latestEl) return;

    if (!numbers.length) {
      latestEl.innerHTML = '<span style="color: #718096;">No bill filed</span>';
      if (badgeEl) badgeEl.textContent = 'N/A';
      if (historyEl) historyEl.innerHTML = '';
      return;
    }

    latestEl.innerHTML = '';
    if (historyEl) historyEl.innerHTML = '';
    let overallBadge = { text: 'N/A', class: 'update' };
    let anyUpdates = false;

    numbers.forEach((num) => {
      const bill = billsData[`${type}${num}`];
      const section = document.createElement('div');
      section.className = 'tfc-bill-status-section';
      if (!bill || bill.error) {
        section.innerHTML = `<div class="tfc-bill-status-header"><strong>${type} ${num}</strong><span class="tfc-status-badge" style="background:#ef4444;color:#fff;">Error</span></div><div class="tfc-bill-latest"><span style="color:#ef4444;font-weight:500;">${escapeHtml(bill && bill.error ? bill.error : 'No data')}</span></div>`;
      } else if (bill.updates && bill.updates.length) {
        anyUpdates = true;
        const latest = bill.updates[0];
        if (latest.badge.class !== 'update') overallBadge = latest.badge;
        section.innerHTML = `<div class="tfc-bill-status-header"><strong>${type} ${num}</strong><span class="tfc-status-badge tfc-badge-${latest.badge.class}">${latest.badge.text}</span></div><div class="tfc-bill-latest"><span class="tfc-status-date">${formatDate(latest.date)}</span>${escapeHtml(latest.description)}</div>`;
        if (historyEl && bill.updates.length > 1 && numbers.length === 1) {
          for (let i = 1; i < bill.updates.length; i++) {
            const u = bill.updates[i];
            const div = document.createElement('div');
            div.className = 'tfc-history-item';
            div.innerHTML = `<span class="tfc-status-date">${formatDate(u.date)}</span>${escapeHtml(u.description)}`;
            historyEl.appendChild(div);
          }
        }
      } else {
        section.innerHTML = `<div class="tfc-bill-status-header"><strong>${type} ${num}</strong><span class="tfc-status-badge">N/A</span></div><div class="tfc-bill-latest"><span style="color:#718096;">No status updates available</span></div>`;
      }
      latestEl.appendChild(section);
    });

    if (badgeEl) {
      badgeEl.textContent = anyUpdates ? overallBadge.text : 'N/A';
      badgeEl.className = `tfc-status-badge tfc-badge-${anyUpdates ? overallBadge.class : 'update'}`;
    }
  }

  class Tracker {
    constructor(el, billsData) {
      this.id = el.dataset.trackerId;
      this.element = el;
      this.hbNumbers = (el.dataset.hb || '').split(',').map((s) => s.trim()).filter(Boolean);
      this.sbNumbers = (el.dataset.sb || '').split(',').map((s) => s.trim()).filter(Boolean);
      this.year = el.dataset.year || '2026';
      this.billsData = billsData;
      this.currentType = this.hbNumbers.length ? 'hb' : 'sb';
    }
    render() {
      this.element.innerHTML = generateTrackerHTML(this.id, this.hbNumbers, this.sbNumbers, this.year);
      this.updateDisplay();
    }
    updateDisplay() {
      const numbers = this.currentType === 'hb' ? this.hbNumbers : this.sbNumbers;
      renderTrackerFeed(this.id, this.billsData, this.currentType.toUpperCase(), numbers);
    }
    switchFeed(billType) {
      this.currentType = billType;
      this.element.querySelectorAll('.tfc-bill-col').forEach((col) => {
        col.classList.toggle('active', col.dataset.billType === billType);
      });
      this.updateDisplay();
    }
    toggleHistory() {
      const section = document.getElementById(`${this.id}-status`);
      if (section) section.classList.toggle('expanded');
    }
  }

  const trackers = {};
  let lastBillsData = null;

  function initTrackers(billsData) {
    lastBillsData = billsData;
    document.querySelectorAll('[data-tracker-id]').forEach((el) => {
      const tracker = new Tracker(el, billsData);
      trackers[tracker.id] = tracker;
      tracker.render();
    });
  }

  // Re-reads data-hb/data-sb/data-year off the element and re-renders — used by pages that
  // swap which bill(s) a tracker points at client-side (e.g. a "policy options" toggle that
  // sets new data-hb/data-sb before calling this). Bills referenced only from such toggles,
  // not from a plain data-tracker-id block, still need to appear somewhere in the tracked
  // HTML for fetch-bill-status.mjs to have pulled their status — see README.
  function reinit(trackerId) {
    const el = document.querySelector(`[data-tracker-id="${trackerId}"]`);
    if (!el || !lastBillsData) return;
    const tracker = new Tracker(el, lastBillsData);
    trackers[trackerId] = tracker;
    tracker.render();
  }

  // ---------- Master "Bill Status Tracker" table ----------

  function renderStatusTable(data) {
    const statusContent = document.getElementById('bill-status-content');
    if (!statusContent) return;

    const rows = [];
    for (const t of data.trackers) {
      const nums = [...t.hbNumbers.map((n) => ({ type: 'HB', number: n })), ...t.sbNumbers.map((n) => ({ type: 'SB', number: n }))];
      for (const { type, number } of nums) {
        const bill = data.bills[`${type}${number}`];
        if (!bill) continue;
        const latest = bill.updates && bill.updates[0];
        rows.push({
          bill: `${type} ${number}`,
          type,
          number,
          year: t.year,
          issueArea: t.issueArea,
          latestStatus: latest ? latest.description : 'No updates available',
          latestDate: latest ? formatDate(latest.date) : '',
          hasScheduledHearing: !!bill.hasScheduledHearing,
          isAlive: !!bill.isAlive,
        });
      }
    }

    if (!rows.length) {
      statusContent.innerHTML = '<div class="tfc-hearings-empty">Unable to load bill statuses</div>';
      return;
    }

    let html = `
      <table class="tfc-bill-status-table">
        <thead><tr><th>Bill Number</th><th>Issue Area</th><th>Latest Status</th></tr></thead>
        <tbody>
    `;
    rows.forEach((r) => {
      const capitolUrl = `https://www.capitol.hawaii.gov/session/measure_indiv.aspx?billtype=${r.type}&billnumber=${r.number}&year=${r.year}`;
      const rowClass = r.hasScheduledHearing ? 'has-hearing' : '';
      const hearingIndicator = r.hasScheduledHearing ? '<span class="hearing-indicator">Hearing Scheduled</span>' : '';
      html += `
        <tr class="${rowClass}" data-alive="${r.isAlive}">
          <td class="bill-number"><a href="${capitolUrl}" target="_blank">${r.bill}</a>${hearingIndicator}</td>
          <td class="issue-area">${r.issueArea}</td>
          <td class="latest-status">${r.latestDate ? `<span class="status-date">${r.latestDate}</span>` : ''}${escapeHtml(r.latestStatus)}</td>
        </tr>
      `;
    });
    html += '</tbody></table>';
    statusContent.innerHTML = html;
    filterBillStatus();
  }

  function toggleBillStatusWidget() {
    const widget = document.getElementById('bill-status-widget');
    if (widget) widget.classList.toggle('collapsed');
  }

  function filterBillStatus() {
    const checkbox = document.getElementById('alive-filter');
    const rows = document.querySelectorAll('#bill-status-content tbody tr');
    const aliveOnly = checkbox ? checkbox.checked : false;
    rows.forEach((row) => {
      row.style.display = !aliveOnly || row.dataset.alive === 'true' ? '' : 'none';
    });
  }

  // ---------- Boot ----------

  async function initAll() {
    const data = await loadData();
    if (!data) {
      const statusContent = document.getElementById('bill-status-content');
      if (statusContent) statusContent.innerHTML = '<div class="tfc-hearings-empty">Unable to load bill statuses</div>';
      return;
    }
    initTrackers(data.bills);
    renderStatusTable(data);
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', initAll);
  } else {
    initAll();
  }

  return {
    switchFeed: (id, type) => trackers[id] && trackers[id].switchFeed(type),
    toggleHistory: (id) => trackers[id] && trackers[id].toggleHistory(),
    toggleTracker: (id) => {
      const content = document.getElementById(`${id}-content`);
      const el = document.querySelector(`[data-tracker-id="${id}"]`);
      if (content && el) el.classList.toggle('expanded');
    },
    toggleBillStatusWidget,
    filterBillStatus,
    reinit,
  };
})();
